# Site settings
title: "Contextus"
description: "Open source, community-driven, forever free. A Homebrew-like service for managing Model Context Protocol (MCP) servers across clients."
url: "https://contextus.sh"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

repository_url: https://github.com/pathintegral-institute/contextus.sh
